<?php

namespace GlpiPlugin\Ticketmigration\Install;

final class Schema
{
    public static function tables(): array
    {
        return [
            'glpi_plugin_ticketmigration_configs' => "CREATE TABLE `glpi_plugin_ticketmigration_configs` (`id` int unsigned NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `value` text, PRIMARY KEY (`id`), UNIQUE KEY `uniq_name` (`name`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            'glpi_plugin_ticketmigration_sourcefiles' => "CREATE TABLE `glpi_plugin_ticketmigration_sourcefiles` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `profiles_id` int unsigned DEFAULT NULL, `users_id` int unsigned NOT NULL, `source_filename` varchar(255) NOT NULL, `internal_filename` char(68) NOT NULL, `sha256` char(64) NOT NULL, `filesize` bigint unsigned NOT NULL, `mime_type` varchar(255) NOT NULL, `schema_fingerprint` char(64) DEFAULT NULL, `csv_config` json DEFAULT NULL, `uploaded_at` timestamp NOT NULL, `expires_at` timestamp NULL, `deleted_at` timestamp NULL, PRIMARY KEY (`id`), UNIQUE KEY `internal_filename` (`internal_filename`), KEY `profile_uploaded` (`profiles_id`,`uploaded_at`), KEY `expires_at` (`expires_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            'glpi_plugin_ticketmigration_profiles' => "CREATE TABLE `glpi_plugin_ticketmigration_profiles` (`id` int unsigned NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `comment` text, `source_name` varchar(255) NOT NULL DEFAULT '', `users_id` int unsigned NOT NULL DEFAULT 0, `entities_id` int unsigned NOT NULL DEFAULT 0, `is_recursive` tinyint NOT NULL DEFAULT 0, `is_private` tinyint NOT NULL DEFAULT 1, `is_ready` tinyint NOT NULL DEFAULT 0, `is_archived` tinyint NOT NULL DEFAULT 0, `archived_at` timestamp NULL, `sourcefiles_id` bigint unsigned DEFAULT NULL, `schema_fingerprint` char(64) DEFAULT NULL, `workflow_step` varchar(40) NOT NULL DEFAULT 'profile_created', `external_id_column` varchar(255) DEFAULT NULL, `csv_config` json DEFAULT NULL, `options` json DEFAULT NULL, `date_creation` timestamp NULL, `date_mod` timestamp NULL, PRIMARY KEY (`id`), KEY `entity_visibility` (`entities_id`,`is_recursive`,`is_private`), KEY `owner` (`users_id`), KEY `archive` (`is_archived`,`archived_at`), KEY `active_source` (`sourcefiles_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            'glpi_plugin_ticketmigration_fieldmappings' => "CREATE TABLE `glpi_plugin_ticketmigration_fieldmappings` (`id` int unsigned NOT NULL AUTO_INCREMENT, `profiles_id` int unsigned NOT NULL, `source_index` int unsigned NOT NULL, `source_name` varchar(255) DEFAULT NULL, `target_key` varchar(255) DEFAULT NULL, `strategy` varchar(50) NOT NULL, `configuration` json DEFAULT NULL, `sort_order` int NOT NULL DEFAULT 0, PRIMARY KEY (`id`), KEY `profile_source` (`profiles_id`,`source_index`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            'glpi_plugin_ticketmigration_valuemappings' => "CREATE TABLE `glpi_plugin_ticketmigration_valuemappings` (`id` int unsigned NOT NULL AUTO_INCREMENT, `profiles_id` int unsigned NOT NULL, `mapping_key` varchar(255) NOT NULL, `source_value_hash` char(64) NOT NULL, `source_value` text NOT NULL, `target_itemtype` varchar(255) DEFAULT NULL, `target_id` int unsigned DEFAULT NULL, `target_value` varchar(255) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `profile_mapping_value` (`profiles_id`,`mapping_key`,`source_value_hash`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            'glpi_plugin_ticketmigration_locationentitymappings' => "CREATE TABLE `glpi_plugin_ticketmigration_locationentitymappings` (`id` int unsigned NOT NULL AUTO_INCREMENT, `profiles_id` int unsigned NOT NULL, `locations_id` int unsigned NOT NULL, `entities_id` int unsigned NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `profile_location` (`profiles_id`,`locations_id`), KEY `entity` (`entities_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            'glpi_plugin_ticketmigration_runs' => "CREATE TABLE `glpi_plugin_ticketmigration_runs` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `profiles_id` int unsigned NOT NULL, `users_id` int unsigned NOT NULL, `entities_id` int unsigned NOT NULL, `source_filename` varchar(255) NOT NULL, `source_internal_name` varchar(255) NOT NULL, `source_hash` char(64) NOT NULL, `status` varchar(40) NOT NULL, `mode` varchar(20) NOT NULL, `started_at` timestamp NULL, `finished_at` timestamp NULL, `total_rows` bigint unsigned NOT NULL DEFAULT 0, `processed_rows` bigint unsigned NOT NULL DEFAULT 0, `success_count` bigint unsigned NOT NULL DEFAULT 0, `warning_count` bigint unsigned NOT NULL DEFAULT 0, `failed_count` bigint unsigned NOT NULL DEFAULT 0, `skipped_count` bigint unsigned NOT NULL DEFAULT 0, `changed_count` bigint unsigned NOT NULL DEFAULT 0, `current_offset` bigint unsigned NOT NULL DEFAULT 0, PRIMARY KEY (`id`), KEY `profile_status` (`profiles_id`,`status`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            'glpi_plugin_ticketmigration_runitems' => "CREATE TABLE `glpi_plugin_ticketmigration_runitems` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `runs_id` bigint unsigned NOT NULL, `row_number` bigint unsigned NOT NULL, `external_id` varchar(255) DEFAULT NULL, `source_hash` char(64) NOT NULL, `status` varchar(40) NOT NULL, `tickets_id` int unsigned DEFAULT NULL, `message` text, `warnings` json DEFAULT NULL, `errors` json DEFAULT NULL, `started_at` timestamp NULL, `finished_at` timestamp NULL, PRIMARY KEY (`id`), UNIQUE KEY `run_row` (`runs_id`,`row_number`), KEY `run_status` (`runs_id`,`status`), KEY `external_id` (`external_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            'glpi_plugin_ticketmigration_externalrefs' => "CREATE TABLE `glpi_plugin_ticketmigration_externalrefs` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `profiles_id` int unsigned NOT NULL, `external_id` varchar(255) NOT NULL, `tickets_id` int unsigned NOT NULL, `source_hash` char(64) NOT NULL, `source_updated_at` timestamp NULL, `imported_at` timestamp NOT NULL, `runs_id` bigint unsigned NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `profile_external` (`profiles_id`,`external_id`), KEY `ticket` (`tickets_id`), KEY `run` (`runs_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        ];
    }
}
